version: '6.0.43.{BUILD}'

image: Visual Studio 2017

install:
    - appveyor-retry choco install InnoSetup
    - git clone https://github.com/c-testsuite/c-testsuite.git
    - copy c-testsuite\tests\single-exec tests\c-testsuite
    - cd \
    - 7z x projects\orangec\src\cc386.zip *
    - set PATH=c:\orangec\bin;c:\cc386\bin;%PATH%;C:\Program Files (x86)\Inno Setup 6
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    - set ORIGPATH=%PATH%
    - set ORANGEC=c:\ORANGEC
    - set LADSOFT_DEV=c:\cc386

branches:
   only:
     - master
     - /v\d*\.\d*\.\d*\.\d*/

configuration:
     - MINGW64 THEN WITH STATIC LIB
     - CLANG THEN WITH STATIC LIB
     - MSVC THEN WITH STATIC LIB
     - MSVC THEN WITH LSCRTL
     - MSVC THEN VIA ASSEMBLY
     - MSVC THEN WITH DEBUG
     - CODE ANALYZER TEST
     - MSIL COMPILER
     - MS WITH PDB

for:
-
      matrix:
            only:
                - configuration: MSVC THEN WITH STATIC LIB
      environment:
          BUILD_PROFILE: MS
      deploy:
          release: Orange C-$(APPVEYOR_REPO_TAG_NAME)
          description: 'Current Release'
          provider: GitHub
          auth_token:
              secure: gOXANm+uz1YSqzv6tHI8/UAlAbA/ofp6o1NNxA+dsVX/jnTZioWTVD3f8Q8S6Un7
          artifact: /.*/
          draft: false
          prerelease: false
          on:
              branch: /v\d*\.\d*\.\d*\.\d*/
              APPVEYOR_REPO_TAG: true
-
      matrix:
            only:
                - configuration: MINGW64 THEN WITH STATIC LIB
      environment:
          BUILD_PROFILE: MINGW64
-
      matrix:
            only:
                - configuration: CLANG THEN WITH STATIC LIB
      environment:
          BUILD_PROFILE: CLANG
-
      matrix:
            only:
                - configuration: MSIL COMPILER
      environment:
          BUILD_PROFILE: OCCIL
-
      matrix:
            only:
                - configuration: MS WITH PDB
      environment:
          BUILD_PROFILE: MSDEBUGBUILD
          MSPDB: YES
-
      matrix:
            only:
                - configuration: MSVC THEN VIA ASSEMBLY
      environment:
          BUILD_PROFILE: MS
          VIAASSEMBLY: YES
-
      matrix:
            only:
                - configuration: MSVC THEN WITH LSCRTL
      environment:
          BUILD_PROFILE: MS
          LSCRTL: YES
-
      matrix:
            only:
                - configuration: MSVC THEN WITH DEBUG
      environment:
          BUILD_PROFILE: MS
          WITHDEBUG: YES
-
      matrix:
            only:
                - configuration: CODE ANALYZER TEST
      environment:
          BUILD_PROFILE: CODEANALYZER


skip_commits:
  files:
    - '**/*.txt'
    - '**/*.doc'
    - '**/*.md'
    - '**/*.html'
 
build_script:
# the appveyor virtual machine reported two processors, so, lets try running parallel compile!
        - ps: |
              cd ..\..
              move projects\orangec .
              mkdir \orangec\temp
              cd orangec\src
              copy omake.exe \orangec\temp
              c:\orangec\appveyorversion.bat
              if ($env:BUILD_PROFILE -eq "OCCIL")
              {
                  # alternate build with OCCIL
                  c:\orangec\temp\omake /DCOMPILER=CLANG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  c:\orangec\bin\occ /V
                  copy omake\omake.exe \orangec\temp
                  c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                  c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  path=$env:ORIGPATH
                  cd ..\tests
                  omake -B /Coccil /DCOMPILER=OCC
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  cd ..\src
              }
              else
              {
                if ($env:BUILD_PROFILE -eq "MSDEBUGBUILD")
                {
                  # Build with Microsoft PDB files
                  c:\orangec\temp\omake /DCOMPILER=MS /DMSPDB=$env:MSPDB fullbuild
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  cd ..\src
                }
                else
                {
                    if ($env:BUILD_PROFILE -eq "CODEANALYZER")
                    {
                      # Build to test code analyzer
                      c:\orangec\temp\omake /DCOMPILER=MS fullbuild
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      cd ..\tests\occpr
                      # generate code
                      omake
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      # analyze
                      omake > q
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      cd ..\..\src
                    }
                    else
                    {
                      # Primary build for Orange C
                      c:\orangec\temp\omake /DCOMPILER=$env:BUILD_PROFILE /DORANGEC_ONLY=YES fullbuild -j:4
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      c:\orangec\bin\occ /V
                      copy omake\omake.exe \orangec\temp
                      c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                      c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DORANGEC_ONLY=YES /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      c:\orangec\bin\occ /V
                      copy omake\omake.exe \orangec\temp
                      c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                      c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DORANGEC_ONLY=YES /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      c:\orangec\bin\occ /V
                      copy omake\omake.exe \orangec\temp
                      c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                      # in this last one we add in OCCIL so it will be in the install packages...
                      if ($env:WITHDEBUG -eq "")
                      {
                          c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG /DWITHMSDOS fullbuild -j:4
                      }
                      else
                      {
                          c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                      }
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      path=$env:ORIGPATH
                      cd ..\tests
                      omake -B /DCOMPILER=OCC
                      if ($LastExitCode -ne 0)
                      {
                          throw "error"
                      }
                      cd ..\src
                    }
                }
              }
              omake /fzip7z.mak
              if ($LastExitCode -ne 0)
              {
                  throw "error"
              }
              cd ..\.. 
              move orangec projects
              cd projects\orangec

artifacts:
  - path: "dist\\*.*"
    name: releasefiles

