image: Visual Studio 2017

install:
    - choco install InnoSetup
    - set PATH=c:\orangec\temp;c:\orangec\bin;%PATH%;C:\Program Files (x86)\Inno Setup 5
    - set ORANGEC=c:\ORANGEC

environment:
    matrix:
        - BUILD_TYPE: MS
        - BUILD_TYPE: MINGW64
 
build_script:
        - cd ..\..
        - move projects\orangec .
        - cd orangec\src
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
        - c:\orangec\src\omake -DCOMPILER=%BUILD_TYPE% 
        - c:\orangec\bin\occ /V
        - cd ..\.. 
        - move orangec projects

artifacts:
  - path: "bin\\ocpp.exe"
    name: ocpp
  - path: "bin\\ocide.exe"
    name: ocide
  - path: "bin\\occpr.exe"
    name: occpr
  - path: "bin\\occ.exe"
    name: occ
  - path: "bin\\coff2ieee.exe"
    name: coff2ieee
  - path: "bin\\omake.exe"
    name: omake
  - path: "bin\\oimplib.exe"
    name: oimplib
  - path: "bin\\obrc.exe"
    name: obrc
  - path: "bin\\ogrep.exe"
    name: ogrep
  - path: "bin\\dlpm.exe"
    name: dlpm
  - path: "bin\\dlpe.exe"
    name: dlpe
  - path: "bin\\dlmz.exe"
    name: dlmz
  - path: "bin\\dlle.exe"
    name: dlle
  - path: "bin\\dlhex.exe"
    name: dlhex
  - path: "bin\\olib.exe"
    name: olib
  - path: "bin\\olink.exe"
    name: olink
  - path: "bin\\oasm.exe"
    name: oasm
  - path: "bin\\ocl.exe"
    name: ocl
  - path: "dist\\*.*"
    name: releasefiles