image: Visual Studio 2017

install:
    - choco install InnoSetup
    - set PATH=c:\orangec\bin;%PATH%;C:\Program Files (x86)\Inno Setup 5
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    - set ORIGPATH=%PATH%
    - set ORANGEC=c:\ORANGEC

environment:
  matrix:
    - BUILD_PROFILE: MINGW64
    - BUILD_PROFILE: MS
 
build_script:
# the appveyor virtual machine reported two processors, so, lets try running parallel compile!
        - cd ..\..
        - move projects\orangec .
        - mkdir \orangec\temp
        - cd orangec\src
        - copy omake.exe \orangec\temp
        - mingw32-make fullbuild --eval="COMPILER=$(BUILD_PROFILE)" -j 4
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild -j:4
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild -j:4 
        - c:\orangec\bin\occ /V
        - copy omake\omake.exe \orangec\temp
        - c:\orangec\temp\omake -DNOMAKEDIR -DCOMPILER=OCC -B fullbuild -j:4 
        - path=%ORIGPATH%
        - cd ..\tests
        - omake -B -j:4
        - cd ..\.. 
        - move orangec projects

artifacts:
  - path: "dist\\*.*"
    name: releasefiles
