version: '6.0.43.{BUILD}'

image: Visual Studio 2017

install:
    - appveyor-retry choco install InnoSetup
    - set PATH=c:\orangec\bin;%PATH%;C:\Program Files (x86)\Inno Setup 6
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
    - set ORIGPATH=%PATH%
    - set ORANGEC=c:\ORANGEC

branches:
   only:
     - master

environment:
  matrix:
    - type: MINGW64
      BUILD_PROFILE: MINGW64
    - type: MS
      BUILD_PROFILE: MS
    - type: MS WITH LSCRTL
      BUILD_PROFILE: MS
      LSCRTL: YES
    - type: MS VIA ASSEMBLY
      BUILD_PROFILE: MS
      VIAASSEMBLY: YES
    - type: MS WITH DEBUG
      BUILD_PROFILE: MS
      WITHDEBUG: YES
    - type: CLANG
      BUILD_PROFILE: CLANG
    - type: MSIL COMPILER
      BUILD_PROFILE: OCCIL

skip_commits:
  files:
    - '**/*.txt'
    - '**/*.doc'
    - '**/*.md'
    - '**/*.html'
    - '*.yml'
 
build_script:
# the appveyor virtual machine reported two processors, so, lets try running parallel compile!
        - ps: |
              echo $env:PATH
              cd ..\..
              move projects\orangec .
              mkdir \orangec\temp
              cd orangec\src
              copy omake.exe \orangec\temp
              c:\orangec\appveyorversion.bat
              if ($env:BUILD_PROFILE -eq "OCCIL")
              {
                  # alternate build with OCCIL
                  c:\orangec\temp\omake /DCOMPILER=CLANG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  c:\orangec\bin\occ /V
                  copy omake\omake.exe \orangec\temp
                  c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                  c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  path=$env:ORIGPATH
                  cd ..\tests
                  omake -B /Coccil /DCOMPILER=OCC
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
              }
              else
              {
                  # Primary build for Orange C
                  c:\orangec\temp\omake /DCOMPILER=$env:BUILD_PROFILE /DORANGEC_ONLY=YES fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  c:\orangec\bin\occ /V
                  copy omake\omake.exe \orangec\temp
                  c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                  c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DORANGEC_ONLY=YES /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  c:\orangec\bin\occ /V
                  copy omake\omake.exe \orangec\temp
                  c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                  c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DORANGEC_ONLY=YES /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  c:\orangec\bin\occ /V
                  copy omake\omake.exe \orangec\temp
                  c:\orangec\temp\omake /DCOMPILER=OCC clean -j:4
                  # in this last one we add in OCCIL so it will be in the install packages...
                  c:\orangec\temp\omake /DNOMAKEDIR /DCOMPILER=OCC /DVIAASSEMBLY=$env:VIAASEMBLY /DLSCRTL=$env:LSCRTL /DWITHDEBUG=$env:WITHDEBUG fullbuild -j:4
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
                  path=$env:ORIGPATH
                  cd ..\tests
                  omake -B /DCOMPILER=OCC
                  if ($LastExitCode -ne 0)
                  {
                      throw "error"
                  }
              }
              cd ..\.. 
              move orangec projects

artifacts:
  - path: "dist\\*.*"
    name: releasefiles
